django_combo_ajax_sample/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from sample.views import index,getdictionary

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', index, name='index'),
    url(r'^api/get-dict/(?P<id>\d+)/$', getdictionary),
]

sample/models.py
from django.db import models

# Create your models here.
class Dictionary(models.Model):
    name = models.CharField(max_length=200)
    parrent = models.ForeignKey('Dictionary',blank=True, null=True)
    create_date = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return u'%s' % (self.name)


class Project(models.Model):
    name = models.CharField(max_length=200)
    shemadgneloba = models.ForeignKey(Dictionary,blank=True, null=True,related_name='shemadgneloba')
    zoma = models.ForeignKey(Dictionary,blank=True, null=True,related_name='zoma')
    erteulis_fasi = models.ForeignKey(Dictionary,blank=True, null=True,related_name='erteulis_fasi')
    create_date = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return u'%s' % (self.name)

sample/forms.py
# -*- coding: utf-8 -*-
__author__ = 'Beka'
from models import Project, Dictionary
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Button

class ProjectForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_class = 'form-horizontal'
        self.helper.add_input(Submit('submit', u'Save'))

    shemadgneloba = forms.ModelChoiceField(queryset=Dictionary.objects.filter(parrent__name=u'შემადგნელობა'))
    #zoma = forms.ModelChoiceField(queryset=Dictionary.objects.none(),required=False)
    zoma = forms.ChoiceField()
    erteulis_fasi = forms.ModelChoiceField(queryset=Dictionary.objects.none(),required=False)

    class Meta:
        model = Project
        fields = ('name', 'shemadgneloba', 'zoma','erteulis_fasi')

sample/views.py
from django.shortcuts import render, get_object_or_404 ,render_to_response,redirect,HttpResponse
from models import Dictionary, Project
from forms import ProjectForm
from django.template import RequestContext
import json

# Create your views here.
def index(request,project_id=None):
    p = get_object_or_404(Project, pk=project_id) if project_id else None
    form = ProjectForm(request.POST or None, instance=p)
    context = RequestContext(request)

    if request.method == 'POST': # save data
        ## ///TODO save data use forms  form.is_valid function
        ## also there is no error handling
        project = Project()
        project.name = request.POST['name']
        # because it's zoma and erteulis_fasi is instance of Dicationary Class
        project.shemadgneloba =  Dictionary.objects.get(id=request.POST['shemadgneloba'])
        project.zoma = Dictionary.objects.get(id=request.POST['zoma'])
        project.erteulis_fasi = Dictionary.objects.get(id=request.POST['erteulis_fasi'])
        project.save()
        return redirect("/")

    projects = Project.objects.order_by('-create_date')
    data = {
        'projects': projects,
        'project_id': project_id,
        'form' : form
    }
    return render_to_response("sample.html", data, context)

# REST API FOR Dictionary OBJECTS
# ///TODO Exception handling
def getdictionary(request,id=None):
    objs = (Dictionary.objects.filter(parrent=id).values('id', 'name'))
    json_objs = json.dumps(list(objs))
    return HttpResponse(json_objs,content_type="application/json")

sample/templates/sample.html
{% extends 'master.html' %}
{% load crispy_forms_tags %}

{% block body %}


<div class="row">
<div class="col-lg-6">
    <h4>  Add Project </h4>
    <form action="/" method="post" class="">
        {% crispy form %}
  </form>
</div>
</div>


<h2>  Project List </h2>

<table class="table">
  <thead>
    <th>პროექტი</th>
    <th>შემადგნელობა</th>
    <th>ზომა</th>
    <th>ერთეულის ფასი</th>

  </thead>

  <tbody>
  {% for itm in projects %}
    <tr>
        <td> {{ itm.name }}</td>
        <td> {{ itm.shemadgneloba }} </td>
        <td> {{ itm.zoma }} </td>
        <td> {{ itm.erteulis_fasi }} </td>
    </tr>
  {% endfor %}
  </tbody>

</table>

<script>
  $(document).ready(function() {


    $("#id_shemadgneloba").change(function() {

      clearComboElements(['#id_zoma','#id_erteulis_fasi']);
      getChildElements('#id_zoma', $("#id_shemadgneloba").val());

    });

    $("#id_zoma").change(function(){

      clearComboElements(['#id_erteulis_fasi']);
      getChildElements('#id_erteulis_fasi', $("#id_zoma").val());

    });


  });
</script>


{% endblock %}

templates/master.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
<!-- Latest compiled and minified JavaScript -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
<!-- Inclide My custom Js library -->
<script src="/static/js/cmbapp.js"></script>


</head>
<body>

<div class="container-fluid">
<h1>  Test Sample </h1>


{%  block body %}

{% endblock %}
</div>
</body>
</html>